'use strict'

const NAMES = [
	'Welcome and Course Methodologies',
	'Welcome and Course Methodologies',
	'Browser, Editor and Terminal Setup',
	'Running and Loading JS',
	'Variables and Statements',
	'Code Quality Tooling with Prettier and ESLint',
	'Types - Introduction',
	'Types - Strings',
	'Types - Numbers',
	'Types - Objects',
	'Types - null and undefined',
	'Types - Booleans and Equality',
	'Functions - Built in',
	'Functions - Custom',
	'Functions - Parameters and Arguments',
	'Different Ways to Declare Functions',
	'Debugging Tools',
	'Scope',
	'Hoisting',
	'Closures',
	'The DOM - Introduction to the document',
	'The DOM - Selecting Elements',
	'The DOM - Element Properties and Methods',
	'The DOM - Working with Classes',
	'The DOM - Build in and Custom Data Attributes',
	'The DOM - Creating HTML',
	'The DOM - HTML from Strings and XSS',
	'The DOM - Traversing and Removing Nodes',
	'The DOM - CARDIO',
	'Events - Event Listener',
	'Events - targets, bubbling, propagation and capture',
	'Events - Prevent Default and Form Events',
	'Events - Accesibility Gotchas and Keyboard Codes',
	'Etch-a-Sketch',
	'Click Outside Modal',
	'Scroll Events and Intersection Observer',
	'Tabs',
	'BEDMAS',
	'Flow Control - If Statements, Function Returns, Truthy, Falsy',
	'Coercion, Ternaries and Conditional Abuse',
	'Case Switch and Animating a Turtle with CSS Variables',
	'Intervals and Timers',
	'Objects',
	'Object Reference vs Values',
	'Maps',
	'Arrays',
	'Array Cardio - Static Methods',
	'Array Cardio - Instance Methods',
	'Array Cardio - Callback Methods and Function Generation',
	'Looping and Iterating - Array .forEach',
	'Looping and Iterating - Mapping',
	'Looping and Iterating - Filter, Find and Higher Order Functions',
	'Looping and Iterating - Reduce',
	'Looping and Iterating - Reduce Exercise',
	'Looping and Iterating - for, for in, for of and while Loops',
	'Face Detection and Censorship',
	'Sarcastic Text Generator',
	'Shopping Form with Custom Events, Delegation and localstorage',
	'Building a Gallery Exercise',
	'Building a Slider',
	'The New Keyword',
	'The this Keyword',
	'Prototype Refactor of the Gallery Exercise',
	'Prototypes and Prototypal Inheritance',
	'Prototype Refactor of the Slider Exercise',
	'bind, call and apply',
	'The Event Loop and Callback Hell',
	'Promises',
	'Promises - Error Handling',
	'Refactoring Callback Hell to Promise Land',
	'Async Await',
	'Async Await Error Handling',
	'Async Await Prompt UI',
	'Async Typer UI - two ways',
	'Ajax and APIs',
	'CORS and Recipes',
	'Dad Jokes',
	'Currency Converter',
	'Modules',
	'Currency Modules Refactor',
	'Dad Jokes Modules Refactor',
	'Bundling and Building with Parcel',
	'using open source npm packages',
	'Security',
	'Web Speech Colours Game',
	'Audio Visualization',
]

const PATH = require('path')
const FS = require('fs')

for (let i = 1; i <= 85; i++) {
	FS.renameSync(
		`/Users/omarrasool/Documents/WesBos - BeginnerJavascript/${
			i + '-' + NAMES[i + 1]
		}.mp4`,
		`/Users/omarrasool/Documents/WesBos - BeginnerJavascript/${
			i + '-' + NAMES[i]
		}.mp4`
	)
	console.log(NAMES[i] + ' Renamed')
}
